name: Actions Tets

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Intall JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Maven Build
        run: mvn clean install

      - name: Hello World
        run: echo "Hello, World!"
